# Generated by Django 4.1 on 2026-01-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_port', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_username', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_password', models.CharField(blank=True, max_length=100, null=True)),
                ('monitor_enabled', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('hash_id', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('callback_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20)),
            ],
            options={
                'verbose_name': 'Monitor Account',
                'verbose_name_plural': 'Monitor Accounts',
                'db_table': 'monitor_accounts',
            },
        ),
        migrations.CreateModel(
            name='RealtimeConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_id', models.CharField(db_index=True, max_length=200)),
                ('public_id', models.CharField(blank=True, max_length=100, null=True)),
                ('member_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(db_index=True, max_length=100)),
                ('conversation_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('dialogue_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_group_chat', models.BooleanField(default=False)),
                ('last_message_text', models.TextField(blank=True, null=True)),
                ('last_message_sender', models.CharField(blank=True, max_length=200, null=True)),
                ('last_message_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('original', 'original'), ('searched', 'searched')], default='searched', max_length=20)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='realtime_monitor.monitoraccount')),
            ],
            options={
                'db_table': 'realtime_conversations',
            },
        ),
        migrations.CreateModel(
            name='RealtimeConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_id', models.CharField(blank=True, max_length=255, null=True)),
                ('member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('original', 'original'), ('searched', 'searched')], default='searched', max_length=20)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='realtime_monitor.monitoraccount')),
            ],
            options={
                'db_table': 'realtime_connections',
            },
        ),
        migrations.AddIndex(
            model_name='realtimeconversation',
            index=models.Index(fields=['account', '-last_activity_at'], name='realtime_co_account_9f4a48_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeconversation',
            index=models.Index(fields=['hash_id'], name='realtime_co_hash_id_7316d1_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeconversation',
            index=models.Index(fields=['-last_message_delivered_at'], name='realtime_co_last_me_217172_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeconversation',
            index=models.Index(fields=['is_group_chat'], name='realtime_co_is_grou_44f61f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='realtimeconversation',
            unique_together={('account', 'hash_id')},
        ),
        migrations.AddIndex(
            model_name='realtimeconnection',
            index=models.Index(fields=['account', '-connected_at'], name='realtime_co_account_c2fad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='realtimeconnection',
            unique_together={('account', 'member_id')},
        ),
    ]
