"""
Django settings for linkedin_connector project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import getpass
import os
import uuid
from enum import EnumMeta, Enum
from pathlib import Path
import sys

import redis

from common.env import is_prod_env, get_env
from middlewares.silence_logging import SilenceLoggingFilter
from middlewares.trace_id import TraceIDFilter

env_obj = get_env()
ENV = os.getenv("Env")
LocalDev = os.environ.get('LocalDev')
CACHE_HOST = os.environ.get('CACHE_HOST', 'localhost')
pod_name = os.environ.get('HOSTNAME', f'{str(uuid.uuid4())}')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q&*q(9vout)$ub-3-=_=4m#hwje=x808ik%6*fpcbqri*hask$'
IS_PROD_ENV = is_prod_env()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PROD_ENV

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # Build-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_crontab',
    'django_filters',

    # Our apps
    'connect.apps.ConnectConfig',
    'crawl.apps.CrawlConfig',
    'wechat.apps.WechatConfig',
    'standard.apps.StandardConfig',
    'processing.apps.ProcessingConfig',
    'mail_chimp.apps.MailChimpConfig',
    'company.apps.CompanyConfig',
    'location.apps.LocationConfig',
    'rexpand_web.apps.RexpandWebConfig',
    'firefox_profile',
    'campaign_manager',
    'auto_connect.apps.AutoConnectConfig',
    'business.apps.BusinessConfig',
    'realtime_monitor.apps.RealtimeMonitorConfig'
]

# if not IS_PROD_ENV:
#     INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    # Trace ID middleware
    'middlewares.trace_id.TraceIDMiddleware',

    # Request middleware
    'middlewares.request.RequestMiddleware',

    # 404 middleware
    'middlewares.not_found.NotFoundMiddleware',

    # Silence logging middleware
    'middlewares.silence_logging.SilenceLoggingMiddleware',

    # response middleware
    'middlewares.response_wrapper.CampaignManagerResponseWrapperMiddleware',

    # 'business.middleware.ForwardProfilesJobsMiddleware',
]
# if not IS_PROD_ENV:
#     MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

# CORS configuration
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'linkedin_realtime_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'linkedin_connector.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# if IS_PROD_ENV:
#     DATABASES = {
#         'default': {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": "postgres",
#             "USER": "root",
#             "PASSWORD": "expand123",
#             "HOST": "linkedin-connector-prod.ctgfrq9pjw56.us-east-1.rds.amazonaws.com",
#             "PORT": "5432",
#             "CONN_MAX_AGE": 999,
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": "postgres",
#             "USER": "root",
#             "PASSWORD": "expand123",
#             "HOST": "linkedin-connector-staging.c6dai18wjyfd.us-east-1.rds.amazonaws.com",
#             "PORT": "5432",
#             "CONN_MAX_AGE": 999,
#         }
#     }

# 配置 Redis 连接
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://{}:6379/1'.format(CACHE_HOST),  # Redis 服务器的地址和端口
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'files/static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'files/media')
DomainName = os.environ.get('DomainName', '')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configure logging
# https://docs.djangoproject.com/en/4.1/ref/settings/#logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'trace_id': {
            '()': TraceIDFilter,
        },
        'silence_logging': {
            '()': SilenceLoggingFilter
        },
    },
    'formatters': {
        'verbose': {
            '()': 'common.log_handle.newline_escape_handler.EscapeNewlineFormatter',
            'format': '{asctime} | {threadName} | {levelname} | {trace_id} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S %z',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['trace_id'],
            'formatter': 'verbose',
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'selenium': {
            'level': 'ERROR',  # Adjust to the level you want
            'handlers': ['console'],  # Assuming you have a console handler
            'propagate': False,
        }
    },
}

RUNNING_TASKS_KEY = f"celery_running_tasks_{pod_name}"

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


# 兼容下不同系统下进程名不一样
def get_firefox_process_name():
    if sys.platform == 'darwin':
        return ['firefox']
    else:
        return ['firefox-bin']


FIREFOX_PROCESS_NAMES = get_firefox_process_name()
CURRENT_SYSTEM_USER = getpass.getuser()
CELERY_SYSTEM_USER = 'root'
GECKODRIVER_PATH = f"{BASE_DIR}/addons/geckodriver"
BROWSER_HEADLESS = False

S3_AWS_ACCESS_KEY_ID = os.environ.get('S3_AWS_ACCESS_KEY_ID')
S3_AWS_SECRET_ACCESS_KEY = os.environ.get('S3_AWS_SECRET_ACCESS_KEY')
S3_REGION_NAME = os.environ.get('S3_REGION_NAME')
S3_BUCKET_NAME = os.environ.get('S3_BUCKET_NAME')

FIREFOX_PROFILE_DIR = 'firefox_profile_dir'

SCREENSHOT_DIR = os.path.join(BASE_DIR, 'screenshot_dir')

SELENIUM_HELPER_PATH = os.path.join(BASE_DIR, 'addons/selenium_helper.xpi')
PROMPT_TEMPLATES = os.path.join(BASE_DIR, 'campaign_manager/prompts')

# 由于团队内的用户， 都是使用的mac， 这里应该是不用设置的， 但是为特殊情况留下个环境变量，方便运行时通过环境变量注入
FIREFOX_BIN_PATH = f'{BASE_DIR}/addons/firefox/firefox'


class WechatRobotKey(str, Enum):
    """
    统一管理微信群通知机器人的KEY
    """
    # excel批量上传岗位功能的KEY
    UPLOAD_JOBS_FROM_EXCEL_KEY = "c6db8970-70b8-4b42-8e78-3d1a18a16805" if IS_PROD_ENV else "c5a6305a-2b36-4a8e-a527-c6b828ca2ff3"

    # FI 功能获取Location和Company的KEY
    FI_GET_LOCATION_AND_COMPANY_KEY = 'c30412de-f79c-4c36-ad20-03d56cd643a4'

    # Hash ID 转化功能的KEY
    HASH_ID_CONVERT_KEY = "19bf1265-ed48-4bc9-8749-210124d32077"

    # LCM 多端登录通知的KEY
    LCM_MULTITERMINAL_ENTRY_KEY = '6c3b7c84-456d-43af-847b-3e2b8d784f79' if IS_PROD_ENV else "e2abf780-0501-4582-a83d-e40b714b4151"

    # Linkedin Message 功能的KEY
    LINKEDIN_MESSAGE_KEY = "1e7fb692-c67c-4fb0-bf70-233cd3d80c46"

    # T1旧数据处理 功能的KEY
    PROCESS_T1_DATA_KEY = "40d85dbb-3f9b-4106-8c8b-a7de196e6338"

    # Tuilink Job Daily 功能的KEY
    TUILINK_JOB_DAILY_KEY = "d1fb22cc-1766-44c1-8646-344c74c967ab" if IS_PROD_ENV else "9005dd09-c63e-4bf5-a138-61f77d8a0dd8"

    # 每日离线岗位抓取情况通知的KEY
    OFFLINE_CRAWL_JOB_DAY = "4af9177b-0331-4bf2-9d01-30d88c2a8304"

    # LKRL 抓取内推人通知的KEY
    LKRL_CRAWL_REFERRER_KEY = "61a1e9fb-0e4b-430a-9eab-0e0c299d2a21" if IS_PROD_ENV else "2142e11f-0120-413e-ba29-f91c1e394b14"

    # 测试使用消息通知的KEY
    TEST_WECHAT_ROBOT_KEY = '4d81aaef-231a-4df0-b41d-840c3d791086' if IS_PROD_ENV else "0371a5bd-4871-4d19-9653-7e4c764c65ba"


# 配置 Redis 客户端
redis_client = redis.StrictRedis(host=CACHE_HOST, port=6379, db=0)

indeed_redis_client = redis.StrictRedis(host=CACHE_HOST, port=6379, db=2)
